config/routes.rb
Rails.application.routes.draw do
  # devise stuff
  devise_for :users

  # info route
  get "/info", to: "info#index"

  # games route
  resources :games

  # user profiles
  get "/user/:id", to: "users#show", as: "user_profile"

  # default to here
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  validates_presence_of :title, :players, :play_time, :difficulty
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
    :validatable, :rememberable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all.sort_by { |game| game.title.downcase }
  end

  # GET /games/1
  # GET /games/1.json
  def show
    # replace \r\n with br tags
    @game.description.gsub!(/\r\n/, "<br/>")
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:title, :players, :play_time, :difficulty, :type_of_game, :category, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # if current_user.nil?
    #   not logged in
  end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_form.html.haml
= form_with(model: game, local: true) do |f|
  .columns.is-desktop
    .column.is-4.is-offset-4
      .top-row-button
        = link_to "Go back to the games", games_path, class: "button"
        -# - if @game.id.nil?
        -#   = link_to "Go back to the games", games_path, class: "button"
        -# - else
        -#   = link_to "Go back to #{@game.title}", @game, class: "button"

      - if @game.errors.any?
        .notification.is-warning
          .content
            %p
              %span.has-text-weight-bold
                = @game.errors.count
                errors 
              prevented this game from saving
            %ul
              - @game.errors.full_messages.each do |msg|
                %li= msg
      .field
        = f.label :title, class: "label"
        .control
          = f.text_field :title, required: true, class: "input", type: "text"
      .field
        = f.label :players, class: "label"
        .control
          = f.text_field :players, required: true, class: "input", type: "text"
      .field
        = f.label :play_time, class: "label"
        .control
          = f.text_field :play_time, required: true, class: "input", type: "text"
      .field
        = f.label :difficulty, class: "label"
        .control
          = f.text_field :difficulty, required: true, class: "input", type: "text"
      .field
        = f.label :type_of_game, class: "label"
        .control
          = f.text_field :type_of_game, required: true, class: "input", type: "text"
      .field
        = f.label :category, class: "label"
        .control
          = f.text_field :category, required: true, class: "input", type: "text"
      .field
        = f.label :description, class: "label"
        .control
          = f.text_area :description, class: "textarea"
      .field.actions
        .control
          - if @game.id.nil?
            = f.submit "Add game", class: "button is-primary is-fullwidth", style: "margin-bottom: 10px;"
          - else
            = f.submit "Save changes", class: "button is-primary is-fullwidth", style: "margin-bottom: 10px;"

app/views/games/edit.html.haml
#edit-game-page.side-padding
  = render 'form', game: @game

app/views/games/index.html.haml
#games-page.side-padding
  
  .columns.is-mobile
    - if user_signed_in? && current_user.is_admin
      .column.is-6
        .top-row-button
          = link_to "Go back home", root_path, class: "button"
      .column.is-6
        .top-row-button
          = link_to "Add a new game", new_game_path, class: "button is-primary"
    - else
      .column.is-12
        .top-row-button
          = link_to "Go back home", root_path, class: "button"
    
  - if notice
    .notification.is-light
      %p#notice= notice
  - if alert
    .notification.is-warning
      %p#notice= alert
  
  %table.table.is-fullwidth
    %thead
      %tr
        %th Title
        %th Players
        %th Play time
        %th Difficulty
        %th Type of game
        %th Category
        - if user_signed_in? && current_user.is_admin?
          %th Edit
          %th Delete
    %tbody
      - @games.each do |game|
        %tr
          %td= game.title
          %td= game.players
          %td= game.play_time
          %td= game.difficulty
          %td= game.type_of_game
          %td= game.category
          - if user_signed_in? && current_user.is_admin?
            %td= link_to fa_icon("pencil-square-o"), edit_game_path(game), class: "button"
            %td= link_to fa_icon("trash"), game_path(game), method: :delete, data: { confirm: "Are you sure?" }, class: "button is-danger"
  
  %p.has-text-weight-bold= "Total games: #{@games.length}"

app/views/games/new.html.haml
#new-game-page.side-padding
  = render 'form', game: @game

app/views/games/show.html.haml
#games-page.side-padding
  .top-row-button
    = link_to "Go back to all games", games_path, class: "button"

  .columns
    .column.is-10
      %h1.title.has-text-weight-bold= @game.title
        
    - if user_signed_in? && current_user.is_admin
      .column.is-1.is-hidden-touch
        = link_to "Edit", edit_game_path(@game), class: "button is-fullwidth is-primary"

      .column.is-1.is-hidden-touch
        = link_to 'Delete', game_path, method: :delete, data: { confirm: "Are you sure?" }, class: "button is-fullwidth is-danger"

  .columns
    .column.is-12
      %p
        %strong Players:
        = @game.players

      %p
        %strong Play time:
        = @game.play_time

      %p
        %strong Difficulty:
        = @game.difficulty

      %p
        %strong Type of game:
        = @game.type_of_game

      %p
        %strong Category:
        = @game.category

      - if !@game.description.nil?
        %p
          %strong Description:
          = simple_format(@game.description, sanitize: false)
  %br/
  %br/
    
  - if user_signed_in? && current_user.is_admin
    .columns.is-mobile.is-hidden-desktop
      .column.is-6
        %p
          = link_to 'Edit', edit_game_path(@game), class: "button is-fullwidth is-primary"
          
      .column.is-6
        %p
          = link_to 'Delete', game_path, method: :delete, data: { confirm: "Are you sure?" }, class: "button is-fullwidth is-danger"
  %br/

app/views/home/index.html.haml
#home-page
  - if notice
    .notification.is-light
      %p#notice= notice

  - if alert
    .notification.is-warning
      %p#notice= alert

  %section#info
    %h1.title 
      %a= link_to "Info 🤔", info_path, class: "light-text"
    %p.subtitle find out what this site is about

  %section#games
    %h1.title 
      %a= link_to "Games 🎲", games_path, class: "light-text"
    %p.subtitle all of our games
      
  %section#movies
    %h1.title 
      %a= link_to "Movies 🎥", root_path, class: "light-text"
    %p.subtitle all of our movies

app/views/info/index.html.haml
#info-page.side-padding
  .top-row-button
    = link_to "Go back home", root_path, class: "button"

  %h1.is-size-3.has-text-weight-bold Hey!

  %p 
    This site has a list of our games and movies in case you wanted to entertain yourself.  
    Hopefully you find it useful, I tried to make it useful. It'd be cool if you found this  
    site useful. If you found it useful, let me (Mike) or Devanne know.                      
  %br/
    
  %p 
    If you need help with anything, you can let
    %a(href="tel:+17244486183") Mike
    or
    %a(href="tel:+17249803173") Devanne
    know

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title deloss 🏠
    = csrf_meta_tags
    = csp_meta_tag
    %meta(charset="UTF-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no")

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      #header.has-text-centered 
        %h1.title.has-text-weight-bold
          = link_to "deloss 🏠", root_path, class: "dark-text"
        %p.dark-text
          - if user_signed_in?
            %a= link_to "view profile", user_profile_path(current_user)
            |
            = link_to "sign out" , destroy_user_session_path, method: :delete
          - else
            %a= link_to "login 🔐", new_user_session_path
        %hr
      = yield

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>